# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/interactive-ml-playground',
                'doc_host': 'https://stepetal.github.io',
                'git_url': 'https://github.com/stepetal/interactive-ml-playground',
                'lib_path': 'interactive_ml_playground'},
  'syms': { 'interactive_ml_playground.core': { 'interactive_ml_playground.core.foo': ( 'core.html#foo',
                                                                                        'interactive_ml_playground/core.py')}}}
